import { Department, Doctor, Testimonial, Facility } from '../types';

export const HOSPITAL_INFO = {
  name: 'We Care Hospital',
  tagline: 'Compassionate Care, Advanced Medicine, Exceptional Outcomes',
  phoneEmergency: '+1 (800) 932-2731',
  phoneAppointments: '+1 (800) 555-CARE',
  email: 'info@wecarehospital.org',
  address: '742 Evergreen Medical Blvd, Metro Health District, CA 90210',
  ambulanceHelpline: '911 or (800) 932-2731',
  visitingHours: 'Daily: 08:00 AM - 08:00 PM (ICU: 11:00 AM - 1:00 PM & 5:00 PM - 7:00 PM)',
  opdHours: 'Monday – Saturday: 8:00 AM – 8:00 PM',
  emergencyHours: '24 Hours, 7 Days a Week, 365 Days a Year',
};

export const HOSPITAL_STATS = [
  { label: 'Licensed Beds', value: '850+' },
  { label: 'Specialist Doctors', value: '180+' },
  { label: 'Annual Surgeries', value: '15,000+' },
  { label: 'Patient Satisfaction', value: '99.2%' },
  { label: 'Years of Service', value: '32+' },
];

export const DEPARTMENTS: Department[] = [
  {
    id: 'cardiology',
    name: 'Cardiology & Vascular Institute',
    tagline: 'Comprehensive heart care from preventive screenings to complex bypass surgeries.',
    description:
      'Our Cardiology Institute is globally recognized for pioneering interventional cardiology, electrophysiology, and minimally invasive cardiac surgeries with 99.4% procedural success.',
    iconName: 'HeartPulse',
    headDoctor: {
      name: 'Dr. Arthur Vance',
      title: 'Chief of Cardiology, MD, FACC',
      avatarUrl:
        'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80',
    },
    keyServices: [
      'Coronary Angiography & Angioplasty',
      'Minimally Invasive Valve Replacement (TAVR)',
      'Cardiac Electrophysiology & Pacemaker Implantation',
      'Advanced Heart Failure Program & LVAD',
      'Pediatric Heart Surgery & Congenital Care',
    ],
    facilities: [
      'Biplane Flat-Panel Cath Lab',
      'Cardiac Intensive Care Unit (CICU)',
      'Non-Invasive Echocardiography & Stress Testing',
    ],
    bedCapacity: 120,
    stats: [
      { label: 'Angioplasties / Year', value: '2,400+' },
      { label: 'Survival Rate', value: '99.4%' },
      { label: 'Door-to-Balloon Time', value: '< 45 mins' },
    ],
    opdHours: 'Mon - Sat: 8:30 AM - 7:00 PM',
    emergencyAvailable: true,
    bannerImage:
      'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'neurology',
    name: 'Neurology & Neurosurgery',
    tagline: 'Precision brain and spinal therapies powered by advanced neuro-navigation.',
    description:
      'Dedicated to treating stroke, epilepsy, neurodegenerative diseases, and complex spinal disorders utilizing state-of-the-art robotic neuro-navigation and biplane neuro-interventions.',
    iconName: 'Brain',
    headDoctor: {
      name: 'Dr. Elena Rostova',
      title: 'Director of Neurosciences, MD, PhD, FAANS',
      avatarUrl:
        'https://images.unsplash.com/photo-1594824813589-fb5ff52b95c3?auto=format&fit=crop&w=600&q=80',
    },
    keyServices: [
      'Comprehensive Stroke Rapid-Response (tPA & Thrombectomy)',
      'Brain Tumor Resection with Intraoperative MRI',
      'Minimally Invasive Spine & Disc Surgery',
      'Epilepsy Monitoring & Deep Brain Stimulation (DBS)',
      'Memory Disorders & Parkinson’s Clinic',
    ],
    facilities: [
      'Intraoperative Neuro-Navigation Suite',
      'Dedicated 24-bed Neuro-ICU',
      'Advanced High-Density Video EEG Monitoring',
    ],
    bedCapacity: 95,
    stats: [
      { label: 'Neuro Surgeries / Year', value: '1,150+' },
      { label: 'Stroke Center Triage', value: 'Certified Level 1' },
      { label: 'Robotic Precision', value: 'Sub-millimeter' },
    ],
    opdHours: 'Mon - Fri: 9:00 AM - 6:00 PM',
    emergencyAvailable: true,
    bannerImage:
      'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'orthopedics',
    name: 'Orthopedics & Joint Care',
    tagline: 'Restoring mobility, athletic performance, and joint freedom.',
    description:
      'Leaders in robotic-assisted knee and hip replacements, sports injury rehabilitation, pediatric orthopedics, and complex trauma bone reconstructions.',
    iconName: 'Activity',
    headDoctor: {
      name: 'Dr. Marcus Sterling',
      title: 'Head of Orthopedic Surgery, MD, FAAOS',
      avatarUrl:
        'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80',
    },
    keyServices: [
      'Robotic Total Knee & Hip Replacement (Mako System)',
      'Arthroscopic Shoulder & ACL Reconstruction',
      'Spinal Decompression & Scoliosis Correction',
      'Sports Injury Acceleration & Physical Therapy',
      'Geriatric Fragility Fracture Management',
    ],
    facilities: [
      'Ultra-Clean Laminar Flow Orthopedic Operating Suites',
      'Robotic Joint Navigation System',
      'On-site Hydrotherapy & Sports Rehabilitation Gym',
    ],
    bedCapacity: 110,
    stats: [
      { label: 'Joint Replacements', value: '1,800+/yr' },
      { label: 'Avg Hospital Stay', value: '24-48 hrs' },
      { label: 'Infection Rate', value: '< 0.2%' },
    ],
    opdHours: 'Mon - Sat: 8:00 AM - 6:30 PM',
    emergencyAvailable: true,
    bannerImage:
      'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'pediatrics',
    name: 'Pediatrics & Neonatal Care',
    tagline: 'Gentle, specialized healthcare for newborns, children, and adolescents.',
    description:
      'Our dedicated Children’s Wing offers comprehensive pediatric medicine, Level III NICU for premature babies, pediatric surgery, and child-friendly outpatient clinics.',
    iconName: 'Baby',
    headDoctor: {
      name: 'Dr. Sophia Martinez',
      title: 'Chief Pediatrician & Neonatologist, MD, FAAP',
      avatarUrl:
        'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80',
    },
    keyServices: [
      'Level III Neonatal Intensive Care Unit (NICU)',
      'Pediatric Emergency & Critical Care',
      'Childhood Immunization & Developmental Milestones',
      'Pediatric Cardiology & Allergy Management',
      'Adolescent Health & Nutrition Counseling',
    ],
    facilities: [
      'Child-Friendly Play & Healing Zones',
      'Warm Neonatal Isolette Pods',
      'Parent-Rooming Pediatric Inpatient Suites',
    ],
    bedCapacity: 80,
    stats: [
      { label: 'Preterm Infants Saved', value: '98.9%' },
      { label: 'Pediatric Consults', value: '18,000+/yr' },
      { label: 'Vaccination Coverage', value: '100%' },
    ],
    opdHours: 'Mon - Sat: 8:00 AM - 8:00 PM',
    emergencyAvailable: true,
    bannerImage:
      'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'oncology',
    name: 'Comprehensive Oncology Center',
    tagline: 'Personalized cancer care with advanced immunotherapy and precision radiation.',
    description:
      'Multidisciplinary tumor board uniting surgical, medical, and radiation oncologists with clinical geneticists to deliver targeted cancer treatments with minimal side effects.',
    iconName: 'ShieldAlert',
    headDoctor: {
      name: 'Dr. Julian Montgomery',
      title: 'Director of Medical Oncology, MD, FACP',
      avatarUrl:
        'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80',
    },
    keyServices: [
      'Targeted Molecular Therapy & Immunotherapy',
      'Precision TrueBeam Radiotherapy & Stereotactic Radiosurgery',
      'Day Care Infusion & Chemotherapy Lounge',
      'Bone Marrow & Stem Cell Transplantation',
      'Integrative Oncology & Psycho-Social Support',
    ],
    facilities: [
      'TrueBeam Linear Accelerator',
      'HEPA-Filtered Stem Cell Transplant Wing',
      'Ergonomic Infusion Recliners with Scenic Views',
    ],
    bedCapacity: 100,
    stats: [
      { label: 'Annual Cancer Patients', value: '4,500+' },
      { label: 'Tumor Board Consensus', value: '100% Cases' },
      { label: 'Clinical Trials Active', value: '25+' },
    ],
    opdHours: 'Mon - Fri: 8:30 AM - 5:30 PM',
    emergencyAvailable: true,
    bannerImage:
      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'emergency',
    name: 'Emergency & Trauma 24/7',
    tagline: 'Instant, certified Level 1 emergency care with zero triage delay.',
    description:
      'Equipped with round-the-clock emergency physicians, acute resuscitation suites, helicopter helipad, and immediate operating room access for critical injuries.',
    iconName: 'Ambulance',
    headDoctor: {
      name: 'Dr. Sarah Lin',
      title: 'Emergency Medicine Chief, MD, FACEP',
      avatarUrl:
        'https://images.unsplash.com/photo-1594824813715-c8c3a1372b6b?auto=format&fit=crop&w=600&q=80',
    },
    keyServices: [
      'Rapid Resuscitation & Polytrauma Management',
      'Code Blue & Acute Cardiac Arrest Intervention',
      'Emergency Toxicological & Poison Control',
      'Disaster Readiness & Mobile Intensive Ambulance Fleet',
      'Direct-to-Cath & Direct-to-CT Stroke Protocols',
    ],
    facilities: [
      'Roof-top Helipad for Aerial Medical Evacuation',
      'Dedicated Trauma Resuscitation Bays',
      'Immediate Access 128-Slice CT Scanner',
    ],
    bedCapacity: 60,
    stats: [
      { label: 'Emergency Admissions', value: '42,000+/yr' },
      { label: 'Initial Triage Time', value: '< 3 mins' },
      { label: 'Emergency Availability', value: '24/7/365' },
    ],
    opdHours: 'Open 24 Hours / 7 Days',
    emergencyAvailable: true,
    bannerImage:
      'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'gynecology',
    name: 'Women’s Health & Maternity',
    tagline: 'Compassionate care celebrating motherhood and comprehensive gynecologic wellness.',
    description:
      'Providing high-risk pregnancy monitoring, natural and gentle birthing suites, advanced laparoscopic reproductive surgeries, and holistic menopause care.',
    iconName: 'Heart',
    headDoctor: {
      name: 'Dr. Claire Beauchamp',
      title: 'Head of Obstetrics & Gynecology, MD, FACOG',
      avatarUrl:
        'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&w=600&q=80',
    },
    keyServices: [
      'Comprehensive Prenatal & High-Risk Obstetric Care',
      'Luxury LDRP (Labor, Delivery, Recovery, Postpartum) Suites',
      'Minimally Invasive Gynecologic Laparoscopy & Hysteroscopy',
      'Fertility Workup & Reproductive Endocrinology',
      'Cervical & Breast Cancer Preventive Screenings',
    ],
    facilities: [
      'Private Spa-Inspired Birthing Suites',
      'Direct Connectivity to Neonatal ICU',
      'Fetal Medicine 4D Sonography Suite',
    ],
    bedCapacity: 75,
    stats: [
      { label: 'Safe Deliveries', value: '3,200+/yr' },
      { label: 'Mother Satisfaction', value: '99.7%' },
      { label: 'Lactation Consultants', value: '24/7 on call' },
    ],
    opdHours: 'Mon - Sat: 8:30 AM - 7:00 PM',
    emergencyAvailable: true,
    bannerImage:
      'https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'dental',
    name: 'Dental & Maxillofacial Care',
    tagline: 'Advanced oral medicine, aesthetic dentistry, and jaw reconstruction.',
    description:
      'Delivering painless root canals, computer-guided dental implants, orthodontics, smile designing, and complex facial trauma surgery with microscopic accuracy.',
    iconName: 'Smile',
    headDoctor: {
      name: 'Dr. Michael Chang',
      title: 'Chief Dental Surgeon, DDS, MS, FICOI',
      avatarUrl:
        'https://images.unsplash.com/photo-1629425733761-caae3b5f2e50?auto=format&fit=crop&w=600&q=80',
    },
    keyServices: [
      'Guided Dental Implants & All-on-4 Restoration',
      'Microscopic Endodontics (Painless Root Canal)',
      'Cosmetic Smile Makeover & Laser Teeth Whitening',
      'Invisalign & Clear Orthodontic Aligners',
      'Oral Cancer Biopsy & Maxillofacial Reconstruction',
    ],
    facilities: [
      'Low-Dose Dental Cone Beam 3D CT (CBCT)',
      'Painless Computerized Local Anesthesia (Wand)',
      'Class B Autoclave Sterilization Protocol',
    ],
    bedCapacity: 20,
    stats: [
      { label: 'Implants Placed', value: '1,400+/yr' },
      { label: 'Success Rate', value: '99.1%' },
      { label: 'Pain-Free Index', value: '97%' },
    ],
    opdHours: 'Mon - Sat: 9:00 AM - 7:30 PM',
    emergencyAvailable: true,
    bannerImage:
      'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1200&q=80',
  },
];

export const DOCTORS: Doctor[] = [
  {
    id: 'doc-vance',
    name: 'Dr. Arthur Vance',
    role: 'Chief Interventional Cardiologist',
    departmentId: 'cardiology',
    departmentName: 'Cardiology & Vascular Institute',
    qualifications: 'MD, FACC, FSCAI (Harvard Medical School)',
    experienceYears: 24,
    rating: 4.9,
    reviewCount: 420,
    avatarUrl:
      'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80',
    bio: 'Dr. Vance has performed over 6,000 coronary interventions and pioneered transcatheter aortic valve techniques. Passionate about cardiovascular risk prevention and complex stent procedures.',
    specializations: ['Transcatheter Aortic Valve (TAVR)', 'Complex Angioplasty', 'Coronary Stenting', 'Preventive Cardiology'],
    education: ['Harvard Medical School (MD)', 'Johns Hopkins Hospital (Cardiology Fellowship)', 'Brigham & Women Hospital (Interventional Fellowship)'],
    availableDays: ['Monday', 'Wednesday', 'Friday'],
    availableHours: '09:00 AM - 03:00 PM',
    consultationFee: 160,
    contactEmail: 'a.vance@wecarehospital.org',
  },
  {
    id: 'doc-rostova',
    name: 'Dr. Elena Rostova',
    role: 'Director of Neurosciences & Skull Base Surgery',
    departmentId: 'neurology',
    departmentName: 'Neurology & Neurosurgery',
    qualifications: 'MD, PhD, FAANS (Stanford University)',
    experienceYears: 19,
    rating: 4.95,
    reviewCount: 380,
    avatarUrl:
      'https://images.unsplash.com/photo-1594824813589-fb5ff52b95c3?auto=format&fit=crop&w=600&q=80',
    bio: 'Pioneer in minimally invasive keyhole neurosurgery and awake craniotomies for brain tumors. Recognized for her humanitarian neurosurgical missions globally.',
    specializations: ['Brain Tumor Resection', 'Cerebrovascular Aneurysms', 'Deep Brain Stimulation', 'Endoscopic Skull Base Surgery'],
    education: ['Stanford University School of Medicine (MD/PhD)', 'UCSF Medical Center (Neurosurgery Residency)', 'Mayo Clinic (Fellowship)'],
    availableDays: ['Tuesday', 'Thursday', 'Saturday'],
    availableHours: '10:00 AM - 04:00 PM',
    consultationFee: 180,
    contactEmail: 'e.rostova@wecarehospital.org',
  },
  {
    id: 'doc-sterling',
    name: 'Dr. Marcus Sterling',
    role: 'Senior Consultant Joint Replacement & Sports Medicine',
    departmentId: 'orthopedics',
    departmentName: 'Orthopedics & Joint Care',
    qualifications: 'MD, FAAOS, FRCS (Oxford University)',
    experienceYears: 21,
    rating: 4.88,
    reviewCount: 310,
    avatarUrl:
      'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80',
    bio: 'Specialist in robotic knee and hip arthroplasty, and athletic ligament reconstruction. Former team orthopedic surgeon for national track and field Olympic athletes.',
    specializations: ['Robotic Mako Joint Replacement', 'ACL & Meniscal Repair', 'Rotator Cuff Surgery', 'Cartilage Regeneration'],
    education: ['Oxford University (BM BCh)', 'Hospital for Special Surgery NY (Orthopedic Residency)', 'Orthopedic Institute Melbourne (Fellowship)'],
    availableDays: ['Monday', 'Tuesday', 'Thursday'],
    availableHours: '08:30 AM - 02:30 PM',
    consultationFee: 150,
    contactEmail: 'm.sterling@wecarehospital.org',
  },
  {
    id: 'doc-martinez',
    name: 'Dr. Sophia Martinez',
    role: 'Chief of Pediatrics & Neonatology',
    departmentId: 'pediatrics',
    departmentName: 'Pediatrics & Neonatal Care',
    qualifications: 'MD, FAAP (Columbia University)',
    experienceYears: 16,
    rating: 4.96,
    reviewCount: 490,
    avatarUrl:
      'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80',
    bio: 'Deeply devoted to neonatal intensive care and child wellness. Dr. Martinez has managed critical premature infant cases with compassion and clinical mastery.',
    specializations: ['Critical Neonatal Care (NICU)', 'Pediatric Asthma & Allergies', 'Infant Nutrition', 'Growth Disorders'],
    education: ['Columbia University Vagelos College of Physicians and Surgeons', 'NewYork-Presbyterian Hospital (Pediatric Residency)'],
    availableDays: ['Monday', 'Wednesday', 'Thursday', 'Friday'],
    availableHours: '09:00 AM - 04:00 PM',
    consultationFee: 130,
    contactEmail: 's.martinez@wecarehospital.org',
  },
  {
    id: 'doc-montgomery',
    name: 'Dr. Julian Montgomery',
    role: 'Head of Clinical Oncology & Immunotherapy',
    departmentId: 'oncology',
    departmentName: 'Comprehensive Oncology Center',
    qualifications: 'MD, FACP (Yale School of Medicine)',
    experienceYears: 22,
    rating: 4.92,
    reviewCount: 260,
    avatarUrl:
      'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80',
    bio: 'A researcher in genomic oncology and checkpoint inhibitors. Leads We Care Hospital tumor boards, curating tailored therapies with maximum effectiveness and comfort.',
    specializations: ['Targeted Immunotherapy', 'Thoracic Oncology', 'Gastrointestinal Cancers', 'Genetic Cancer Profiling'],
    education: ['Yale School of Medicine (MD)', 'Memorial Sloan Kettering (Hematology/Oncology Fellowship)'],
    availableDays: ['Tuesday', 'Wednesday', 'Friday'],
    availableHours: '10:00 AM - 03:00 PM',
    consultationFee: 190,
    contactEmail: 'j.montgomery@wecarehospital.org',
  },
  {
    id: 'doc-lin',
    name: 'Dr. Sarah Lin',
    role: 'Medical Director of Emergency Services',
    departmentId: 'emergency',
    departmentName: 'Emergency & Trauma 24/7',
    qualifications: 'MD, FACEP (Johns Hopkins University)',
    experienceYears: 17,
    rating: 4.94,
    reviewCount: 510,
    avatarUrl:
      'https://images.unsplash.com/photo-1594824813715-c8c3a1372b6b?auto=format&fit=crop&w=600&q=80',
    bio: 'Commanding acute trauma triage and rapid resuscitation protocols. Dr. Lin coordinates the hospital 24/7 disaster preparedness and emergency air-lift response.',
    specializations: ['Polytrauma Triage', 'Acute Cardiac Life Support', 'Point-of-Care Ultrasound (POCUS)', 'Disaster Medicine'],
    education: ['Johns Hopkins University (MD)', 'Denver Health Medical Center (Emergency Medicine Residency)'],
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableHours: '24/7 Shift Rotation',
    consultationFee: 140,
    contactEmail: 's.lin@wecarehospital.org',
  },
  {
    id: 'doc-beauchamp',
    name: 'Dr. Claire Beauchamp',
    role: 'Senior Consultant Obstetrician & Gynecologist',
    departmentId: 'gynecology',
    departmentName: 'Women’s Health & Maternity',
    qualifications: 'MD, FACOG, MRCOG (London)',
    experienceYears: 18,
    rating: 4.97,
    reviewCount: 440,
    avatarUrl:
      'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&w=600&q=80',
    bio: 'Committed to empowering mothers with personalized, respectful birthing experiences and pioneering minimally invasive laparoscopic solutions for women’s wellness.',
    specializations: ['High-Risk Pregnancies', 'Natural & Water Birthing', 'Laparoscopic Hysterectomy', 'Endometriosis Treatment'],
    education: ['King’s College London (MBBS)', 'McGill University (OB/GYN Residency)', 'Imperial College (Fellowship)'],
    availableDays: ['Monday', 'Wednesday', 'Saturday'],
    availableHours: '09:00 AM - 04:00 PM',
    consultationFee: 150,
    contactEmail: 'c.beauchamp@wecarehospital.org',
  },
  {
    id: 'doc-chang',
    name: 'Dr. Michael Chang',
    role: 'Chief Dental & Maxillofacial Specialist',
    departmentId: 'dental',
    departmentName: 'Dental & Maxillofacial Care',
    qualifications: 'DDS, MS, FICOI (UCLA School of Dentistry)',
    experienceYears: 15,
    rating: 4.89,
    reviewCount: 330,
    avatarUrl:
      'https://images.unsplash.com/photo-1629425733761-caae3b5f2e50?auto=format&fit=crop&w=600&q=80',
    bio: 'Dedicated to gentle, fear-free dentistry with computerized 3D smile planning, porcelain veneers, and computer-guided immediate dental implants.',
    specializations: ['Immediate Load Dental Implants', 'Aesthetic Smile Design', 'Wisdom Tooth Micro-Surgery', 'TMJ Disorder Therapy'],
    education: ['UCLA School of Dentistry (DDS)', 'University of Michigan (Oral Surgery Specialty)'],
    availableDays: ['Tuesday', 'Wednesday', 'Thursday', 'Saturday'],
    availableHours: '09:30 AM - 05:00 PM',
    consultationFee: 120,
    contactEmail: 'm.chang@wecarehospital.org',
  },
  {
    id: 'doc-patel',
    name: 'Dr. Rajesh Patel',
    role: 'Consultant Interventional Neurologist',
    departmentId: 'neurology',
    departmentName: 'Neurology & Neurosurgery',
    qualifications: 'MD, DM, FINR (Duke University)',
    experienceYears: 14,
    rating: 4.87,
    reviewCount: 220,
    avatarUrl:
      'https://images.unsplash.com/photo-1622902046580-2b47f47f5471?auto=format&fit=crop&w=600&q=80',
    bio: 'Specialist in acute mechanical thrombectomy for ischemic stroke, coil embolization of brain aneurysms, and carotid artery stenting.',
    specializations: ['Stroke Thrombectomy', 'Carotid Stenting', 'Aneurysm Coiling', 'Headache & Migraine Therapy'],
    education: ['Duke University School of Medicine (MD)', 'Cleveland Clinic (Neurology Residency)'],
    availableDays: ['Monday', 'Wednesday', 'Friday'],
    availableHours: '09:00 AM - 02:00 PM',
    consultationFee: 165,
    contactEmail: 'r.patel@wecarehospital.org',
  },
  {
    id: 'doc-kaufman',
    name: 'Dr. Hannah Kaufman',
    role: 'Consultant Pediatric Surgeon & Urologist',
    departmentId: 'pediatrics',
    departmentName: 'Pediatrics & Neonatal Care',
    qualifications: 'MD, FAAP, FACS (University of Pennsylvania)',
    experienceYears: 13,
    rating: 4.93,
    reviewCount: 280,
    avatarUrl:
      'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?auto=format&fit=crop&w=600&q=80',
    bio: 'Expertise in pediatric congenital anomalies, laparoscopic hernia repairs, and minimally invasive pediatric gastrointestinal surgeries.',
    specializations: ['Pediatric Laparoscopic Surgery', 'Congenital Defect Repair', 'Pediatric Urology', 'Neonatal Surgical Care'],
    education: ['Perelman School of Medicine at Penn (MD)', 'Children’s Hospital of Philadelphia (CHOP)'],
    availableDays: ['Tuesday', 'Thursday', 'Friday'],
    availableHours: '08:30 AM - 03:30 PM',
    consultationFee: 155,
    contactEmail: 'h.kaufman@wecarehospital.org',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't-1',
    patientName: 'Eleanor Davis',
    location: 'Metro District, CA',
    department: 'Cardiology & Vascular Institute',
    doctorName: 'Dr. Arthur Vance',
    content:
      'When I arrived at We Care Hospital with chest discomfort, the emergency and cardiology teams sprang into action in minutes. Dr. Vance placed a stent with zero complications. The nurses were angels, and I felt completely protected.',
    rating: 5,
    date: 'August 14, 2026',
  },
  {
    id: 't-2',
    patientName: 'David H. Reynolds',
    location: 'Silicon Valley, CA',
    department: 'Orthopedics & Joint Care',
    doctorName: 'Dr. Marcus Sterling',
    content:
      'After suffering chronic knee osteoarthritis for 6 years, Dr. Sterling conducted robotic knee replacement surgery. I was walking with minimal discomfort the next morning! Today, I’m back hiking with my grandkids.',
    rating: 5,
    date: 'July 29, 2026',
  },
  {
    id: 't-3',
    patientName: 'Rachel & Kevin Chen',
    location: 'Pasadena, CA',
    department: 'Pediatrics & Neonatal Care',
    doctorName: 'Dr. Sophia Martinez',
    content:
      'Our twin babies were born 7 weeks early. The Level III NICU at We Care Hospital was breathtakingly high-tech yet so profoundly caring. Dr. Martinez gave us confidence each day. Both babies are thriving and healthy!',
    rating: 5,
    date: 'September 3, 2026',
  },
  {
    id: 't-4',
    patientName: 'Robert Gomez',
    location: 'Glendale, CA',
    department: 'Neurology & Neurosurgery',
    doctorName: 'Dr. Elena Rostova',
    content:
      'Dr. Rostova diagnosed my acoustic neuroma and executed a precision skull-base procedure. My facial nerves and hearing were fully preserved. The kindness of the entire hospital staff made an insurmountable trial manageable.',
    rating: 5,
    date: 'June 18, 2026',
  },
];

export const HOSPITAL_FACILITIES: Facility[] = [
  {
    title: 'Level 1 Trauma & Emergency',
    description: 'Round-the-clock emergency surgeons, 6 trauma bays, and rooftop helipad for rapid aerial transfers.',
    iconName: 'ShieldAlert',
    highlight: '24/7 Zero Wait Triage',
  },
  {
    title: 'Advanced Robotic Surgery',
    description: 'Da Vinci Xi and Mako robotic systems delivering millimeter-level precision and accelerated patient recovery.',
    iconName: 'Cpu',
    highlight: 'Minimally Invasive',
  },
  {
    title: '3.0 Tesla MRI & 128-Slice CT',
    description: 'Next-generation low-radiation imaging suites providing rapid, ultra-high resolution diagnostics.',
    iconName: 'Scan',
    highlight: 'Same-Day Diagnostics',
  },
  {
    title: '24/7 Smart In-House Pharmacy',
    description: 'Fully automated barcode-verified medication dispensing with drive-through and bedside delivery.',
    iconName: 'Pill',
    highlight: '100% Genuine Medicine',
  },
  {
    title: 'Level III Neonatal & Pediatric ICU',
    description: 'Dedicated critical care for premature infants and pediatric patients with continuous telemetry monitoring.',
    iconName: 'Baby',
    highlight: 'Specialized Child Care',
  },
  {
    title: 'Comprehensive Rehabilitation & PT',
    description: 'Hydrotherapy pools, gait trainers, and experienced physiotherapists returning patients to active life.',
    iconName: 'Activity',
    highlight: 'Personalized Recovery',
  },
];

export const ACCREDITATIONS = [
  { name: 'Joint Commission International (JCI)', code: 'Gold Seal of Approval' },
  { name: 'NABH Super Specialty Accreditation', code: 'National Standards Certified' },
  { name: 'ISO 9001:2015 Healthcare Quality', code: 'Certified Clinical Safety' },
  { name: 'College of American Pathologists (CAP)', code: 'Gold Standard Lab Accreditation' },
];
